# Generated by Django 5.2.5 on 2026-08-17 04:01

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('VALIDATING', '검증'), ('PREPROCESSING', '전처리'), ('RUNNING', '추론'), ('POSTPROCESSING', '후처리'), ('COMPLETED', '완료'), ('FAILED', '실패')], default='PENDING', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('model_name', models.CharField(max_length=120)),
                ('model_version_name', models.CharField(max_length=50)),
                ('inference_mode', models.CharField(default='mock', max_length=20)),
                ('device', models.CharField(blank=True, max_length=80)),
                ('mixed_precision', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('preprocessing_seconds', models.FloatField(blank=True, null=True)),
                ('inference_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('exception_history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.modelversion')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmentation_file', models.FileField(upload_to=core.models.result_upload_path)),
                ('overlay_file', models.ImageField(upload_to=core.models.result_upload_path)),
                ('metrics_file', models.FileField(upload_to=core.models.result_upload_path)),
                ('whole_tumor_voxels', models.PositiveBigIntegerField(default=0)),
                ('tumor_core_voxels', models.PositiveBigIntegerField(default=0)),
                ('enhancing_tumor_voxels', models.PositiveBigIntegerField(default=0)),
                ('whole_tumor_cm3', models.FloatField(default=0)),
                ('tumor_core_cm3', models.FloatField(default=0)),
                ('enhancing_tumor_cm3', models.FloatField(default=0)),
                ('spacing', models.JSONField(default=list)),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='core.analysisjob')),
            ],
        ),
        migrations.CreateModel(
            name='JobReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVED', '승인'), ('REJECTED', '반려')], max_length=10)),
                ('comment', models.TextField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.analysisjob')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MRIStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('t1', models.FileField(upload_to=core.models.anonymized_upload_path)),
                ('t1ce', models.FileField(upload_to=core.models.anonymized_upload_path)),
                ('t2', models.FileField(upload_to=core.models.anonymized_upload_path)),
                ('flair', models.FileField(upload_to=core.models.anonymized_upload_path)),
                ('reference_mask', models.FileField(blank=True, upload_to=core.models.anonymized_upload_path)),
                ('shape', models.JSONField(default=list)),
                ('affine', models.JSONField(default=list)),
                ('spacing', models.JSONField(default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mri_studies', to='core.project')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.mristudy'),
        ),
    ]
