# Generated by Django 5.2.5 on 2026-08-17 04:35

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_analysisjob_analysisresult_jobreview_mristudy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mristudy',
            name='equipment_code',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='mristudy',
            name='hospital_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='mristudy',
            name='timepoint_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='mristudy',
            name='timepoint_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mristudy',
            name='treatment_event',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('hazard', models.CharField(max_length=250)),
                ('hazardous_situation', models.TextField()),
                ('harm', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazards', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='MaskCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrected_mask_file', models.FileField(upload_to=core.models.result_upload_path)),
                ('corrected_overlay_file', models.ImageField(blank=True, upload_to=core.models.result_upload_path)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING_REVIEW', '재검토 대기'), ('APPROVED', '승인'), ('REJECTED', '반려')], default='PENDING_REVIEW', max_length=20)),
                ('whole_tumor_voxels', models.PositiveBigIntegerField(default=0)),
                ('tumor_core_voxels', models.PositiveBigIntegerField(default=0)),
                ('enhancing_tumor_voxels', models.PositiveBigIntegerField(default=0)),
                ('whole_tumor_cm3', models.FloatField(default=0)),
                ('tumor_core_cm3', models.FloatField(default=0)),
                ('enhancing_tumor_cm3', models.FloatField(default=0)),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='core.analysisresult')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVED', '승인'), ('REJECTED', '반려')], max_length=10)),
                ('comment', models.TextField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('correction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.maskcorrection')),
            ],
        ),
        migrations.CreateModel(
            name='Nonconformity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('ANALYSIS_FAILURE', '분석 실패'), ('REVIEW_REJECTION', '검토 반려'), ('OTHER', '기타')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconformities', to='core.analysisjob')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonconformities', to='core.project')),
                ('rejected_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconformities', to='core.jobreview')),
            ],
        ),
        migrations.CreateModel(
            name='CAPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('preventive_action', models.TextField(blank=True)),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', '등록'), ('INVESTIGATING', '조사'), ('ACTION_IN_PROGRESS', '조치 진행'), ('EFFECTIVENESS_REVIEW', '효과성 검토'), ('CLOSED', '종료')], default='OPEN', max_length=30)),
                ('effectiveness_result', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closure_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_capas', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_capas', to=settings.AUTH_USER_MODEL)),
                ('nonconformity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capa', to='core.nonconformity')),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('probability', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('initial_risk', models.PositiveSmallIntegerField(default=1)),
                ('residual_severity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('residual_probability', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('residual_risk', models.PositiveSmallIntegerField(default=1)),
                ('rationale', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to='core.analysisjob')),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.hazard')),
                ('rejected_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to='core.jobreview')),
            ],
        ),
        migrations.CreateModel(
            name='RiskControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_measure', models.TextField()),
                ('verification', models.TextField(blank=True)),
                ('implemented', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='core.riskassessment')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.project')),
            ],
        ),
        migrations.AddField(
            model_name='mristudy',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timepoints', to='core.subject'),
        ),
        migrations.AddConstraint(
            model_name='mristudy',
            constraint=models.UniqueConstraint(fields=('subject', 'timepoint_code'), name='unique_subject_timepoint_code'),
        ),
        migrations.AddConstraint(
            model_name='mristudy',
            constraint=models.UniqueConstraint(fields=('subject', 'timepoint_order'), name='unique_subject_timepoint_order'),
        ),
        migrations.AddConstraint(
            model_name='hazard',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='unique_project_hazard_code'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('project', 'subject_code'), name='unique_project_subject_code'),
        ),
    ]
